name: build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Build tweetnacl-java from sources
        run: |
          git clone https://github.com/InstantWebP2P/tweetnacl-java.git
          cd tweetnacl-java
          mvn  install
      - name: Build
        run: ./gradlew build
