name: Integration Test
on:
  push:
    branches-ignore:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Build
        env:
          E2E_RPC_URL: ${{ secrets.E2E_RPC_URL }}
          E2E_SECRET_KEY: ${{ secrets.E2E_SECRET_KEY }}
        run: ./gradlew integrationTest
